Update rebar.config
We are facing cloning issue, currently the builds are getting  failed while getting deps from webmachine (it is an open source repository) with below error:
Cloning into 'mochiweb'...
Build timed out (after 10 minutes). Marking the build as failed.
Build was aborted
ERROR: git clone -n git://github.com/basho/mochiweb.git mochiweb failed with error: 143 and output:
Cloning into 'mochiweb'...
 o fix above issue, it seems we need to change gerrit mirror  from "git:" to "https:"

Please do the needful as soon as possible eg {git,"https://github.com/basho/mochiweb.git",
                           {tag,"1.5.1p7"}}